
services:
  # 1. The Database Service
  db:
    image: postgres:15
    container_name: cxr_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  # Saves your DB data so it isn't lost on restart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. The FastAPI Service
  api:
    image: mohammad4242/myapi:latest
    container_name: cxr_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Wait until PostgreSQL is actually ready, not just started
    volumes:
      - ./images:/app/images  # Syncs the saved images to your Linux folder
volumes:
  pg_data:  # Defines the volume for the database
